"""empty message

Revision ID: b4b998bd4078
Revises: 
Create Date: 2023-06-11 12:58:37.051261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b998bd4078'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b_title', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('b_img_src', sa.String(length=400), nullable=True))
        batch_op.drop_column('b_summary')
        batch_op.drop_column('b_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b_name', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('b_summary', sa.VARCHAR(length=10000), nullable=True))
        batch_op.drop_column('b_img_src')
        batch_op.drop_column('b_title')

    # ### end Alembic commands ###
